import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Replace these placeholder values with the file generated by
/// `flutterfire configure`. Keeping it under version control avoids accidental
/// deletions when switching branches, and the CLI will overwrite it with the
/// real project configuration when you run it locally.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'WEB_API_KEY',
    appId: '1:000000000000:web:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'upsglam-demo',
    storageBucket: 'upsglam-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ANDROID_API_KEY',
    appId: '1:000000000000:android:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'upsglam-demo',
    storageBucket: 'upsglam-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'IOS_API_KEY',
    appId: '1:000000000000:ios:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'upsglam-demo',
    storageBucket: 'upsglam-demo.appspot.com',
    iosBundleId: 'ec.ups.upsglam.upsglamMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'MACOS_API_KEY',
    appId: '1:000000000000:macos:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'upsglam-demo',
    storageBucket: 'upsglam-demo.appspot.com',
    iosBundleId: 'ec.ups.upsglam.upsglamMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'WINDOWS_API_KEY',
    appId: '1:000000000000:windows:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'upsglam-demo',
    storageBucket: 'upsglam-demo.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'LINUX_API_KEY',
    appId: '1:000000000000:linux:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'upsglam-demo',
    storageBucket: 'upsglam-demo.appspot.com',
  );
}
